// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3FI7KnkV5HvI4mTZHfWdGfsllG5WCwqc',
    appId: '1:814899187812:android:83e2410982f8b91dfc8f71',
    messagingSenderId: '814899187812',
    projectId: 'flutter03-7dc78',
    storageBucket: 'flutter03-7dc78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnAcWohxt2TA7zvUSReI4EJcbi2snrALw',
    appId: '1:814899187812:ios:62ed02f63c367fa7fc8f71',
    messagingSenderId: '814899187812',
    projectId: 'flutter03-7dc78',
    storageBucket: 'flutter03-7dc78.appspot.com',
    iosBundleId: 'com.example.flutter03',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxfRMKRJtH0T4XePyC7UaNJAjuXffapcA',
    appId: '1:814899187812:web:eb2b1391a692e740fc8f71',
    messagingSenderId: '814899187812',
    projectId: 'flutter03-7dc78',
    authDomain: 'flutter03-7dc78.firebaseapp.com',
    storageBucket: 'flutter03-7dc78.appspot.com',
  );

}